steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/positive-guild-346018/my-image', '.']
    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/positive-guild-346018/my-image']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args: ['run', 'deploy', 'ttl-18h', '--image', 'gcr.io/positive-guild-346018/my-image', '--region', 'us-east1']
    images:
    - gcr.io/positive-guild-346018/my-image